### ISSUE TITLE
it is just csss lol

### ISSUE THREAD

**Issue by akshatsinghania** [PwnFunction/Blank-Rick-Roll#1]

**Comment by akshatsinghania** [comment]
btw heres the real issue https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by ghost** [comment]
> btw heres the real issue https://www.youtube.com/watch?v=dQw4w9WgXcQ

Of course

**Comment by chirag-droid** [comment]
So what's the status of issue? The issue seems complicated to me.

**Comment by LeonetKenner** [comment]
reee mistake
