### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by zghwi** [PwnFunction/Blank-Rick-Roll#3]
I prefer to change the domain name, because when the user sees the URL (`https://therickroll.com`) will know that this is a rick roll, except if you change the text (like [free discord nitro](https://therickroll.com))

oh and btw here is a cool project I made: [https://github.com/zplusfour/news-app](https://therickroll.com)

**Comment by lnfernal** [comment]
you can hover over your news app and it goes to https://therickroll.com, good thing I didn't click it lol

**Comment by AmazingMech2418** [comment]
> you can hover over your news app and it goes to https://therickroll.com, good thing I didn't click it lol

There are ways to cover up that part too (I've tested it before), but just not in GitHub issues. Only your own websites.

**Comment by zghwi** [comment]
> you can hover over your news app and it goes to https://therickroll.com, good thing I didn't click it lol

lmfaoooo

**Comment by Cadris** [comment]
> I prefer to change the domain name, because when the user sees the URL (`https://therickroll.com`) will know that this is a rick roll, except if you change the text (like [free discord nitro](https://therickroll.com))
> 
> oh and btw here is a cool project I made: [https://github.com/zplusfour/news-app](https://therickroll.com)

O well
